### ISSUE TITLE
04-parser run erro

### ISSUE THREAD

**Issue by 827346462** [NVIDIA/trt-samples-for-hackathon-cn#10]
I use nvcr.io/nvidia/pytorch :21.10-py3 .

Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3553, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 424, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Exception ignored in: 'cuda._lib.ccudart.utils.cudaPythonGlobal.lazyInit'
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3553, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 424, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Traceback (most recent call last):
  File "pyTorchToTensorRT.py", line 49, in <module>
    cudart.cudaDeviceSynchronize()
  File "cuda/cudart.pyx", line 6923, in cuda.cudart.cudaDeviceSynchronize
  File "cuda/ccudart.pyx", line 25, in cuda.ccudart.cudaDeviceSynchronize
  File "cuda/_cuda/ccuda.pyx", line 3853, in cuda._

**Comment by wili-65535** [comment]
Which sample did you run so you got the such error?
