### ISSUE TITLE
pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by 18780165950** [NVIDIA/trt-samples-for-hackathon-cn#103]
Traceback (most recent call last):
  File "/netdrive/project/tangzihang/trt-samples-for-hackathon-cn-master/trt-samples-for-hackathon-cn-master/cookbook/01-SimpleDemo/TensorRT8.5/main_1.py", line 104, in <module>
    run()                                                                       # create a serialized network of TensorRT and do inference
  File "/netdrive/project/tangzihang/trt-samples-for-hackathon-cn-master/trt-samples-for-hackathon-cn-master/cookbook/01-SimpleDemo/TensorRT8.5/main_1.py", line 38, in run
    builder = trt.Builder(logger)                                           # create Builder
TypeError: pybind11::init(): factory function returned nullptr

**Comment by 18780165950** [comment]
how to solve this error？ help！
