### ISSUE TITLE
module 'tensorrt' has no attribute 'IDebugListener' in utils

### ISSUE THREAD

**Issue by CDalezyb** [NVIDIA/trt-samples-for-hackathon-cn#109]
(py38) dale@ubuntu:~/DaleData/trt-samples-for-hackathon-cn/trtcookbook/00-Data$ python get_model_part1.py
Traceback (most recent call last):
  File "get_model_part1.py", line 31, in <module>
    from utils import case_mark
  File "/home/dale/DaleData/trt-samples-for-hackathon-cn/trtcookbook/00-Data/../include/utils.py", line 18, in <module>
    from utils_class import *  # isort:disable
  File "/home/dale/DaleData/trt-samples-for-hackathon-cn/trtcookbook/00-Data/../include/utils_class.py", line 52, in <module>
    class MyDebugListener(trt.IDebugListener):
AttributeError: module 'tensorrt' has no attribute 'IDebugListener'

**Comment by wili-65535** [comment]
I'm sorry 'trt.IDebugListener' only supported since TensorRT-10.0. You can upgrade to a newer version or just drop this class in the cookbook.
